// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_yay_you_did_it = "CgkI4OHyiKIOEAIQBQ"; // <GPGSID>
        public const string achievement_ooh_thats_gotta_hurt = "CgkI4OHyiKIOEAIQAg"; // <GPGSID>
        public const string achievement_no_stress_no_mess = "CgkI4OHyiKIOEAIQCA"; // <GPGSID>
        public const string achievement_so_so_close = "CgkI4OHyiKIOEAIQBg"; // <GPGSID>
        public const string achievement_begin_the_tilt = "CgkI4OHyiKIOEAIQAQ"; // <GPGSID>
        public const string achievement_banished_to_the_shadow_realm = "CgkI4OHyiKIOEAIQBA"; // <GPGSID>
        public const string achievement_obstacle_smash = "CgkI4OHyiKIOEAIQAw"; // <GPGSID>
        public const string achievement_this_game_is_actually_hard = "CgkI4OHyiKIOEAIQCg"; // <GPGSID>
        public const string achievement_instructions_unclear_got_stuck_in_a_cube = "CgkI4OHyiKIOEAIQCQ"; // <GPGSID>
        public const string achievement_too_ez = "CgkI4OHyiKIOEAIQBw"; // <GPGSID>

}

